#!/usr/bin/env bash

cp aliases ~/.tools-aliases

if ! grep -q '~/.tools-aliases' ~/.bashrc 
then echo '. ~/.tools-aliases' >> ~/.bashrc
fi

if ! grep  -q '~/.tools-aliases' ~/.zshrc
then echo '. ~/.tools-aliases' >> ~/.zshrc
fi

exit 0
